services:
  small-to-do:
    build: .
    command: ["node", "build"]
    environment:
      PORT: 5173
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: small_to_do
      POSTGRES_HOST: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/small_to_do
    ports:
      - 5173:5173
    depends_on:
      - postgres
      - postgraphile

  postgraphile:
    image: graphile/postgraphile:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/small_to_do
      POSTGRAPHILE_OPTIONS: --watch --enhance-graphiql --cors
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: small_to_do
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
