version: '3.8'

services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    networks:
      - rabbitmq_default

networks:
  rabbitmq_default:
    external: true
    name: rabbitmq_default
