version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
