version: '3.8'

services:
  nestjs-app:
    build: .
    ports:
      - "3001:3000"
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672

networks:
  default:
    external: true
    name: rabbitmq_default
